In [ ]:
# ==============================================================================
# ATIVIDADE 2: CHATBOT VERSÃO 2 (DECISION TREE)
# ==============================================================================

import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.tree import DecisionTreeClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split

# 1. Carregar dataset do CSV
df = pd.read_csv('dataset_moveis_100.csv')

# 2. Divisão estratificada de treino e teste (30% para teste)
X_train, X_test, y_train, y_test = train_test_split(
    df['texto'],
    df['intencao'],
    test_size=0.30,
    random_state=42,
    stratify=df['intencao']
)

# 3. Construir a Pipeline utilizando TF-IDF + Decision Tree
pipeline_dt = Pipeline([
    ('vectorizer', TfidfVectorizer()),
    ('classifier', DecisionTreeClassifier(random_state=42))
])

# 4. Treinar a Pipeline
pipeline_dt.fit(X_train, y_train)

# 5. Fazer as previsões nos dados de teste
y_pred = pipeline_dt.predict(X_test)

# 6. Exibir a Matriz de Confusão
print("\n=== MATRIZ DE CONFUSÃO ===")
print(confusion_matrix(y_test, y_pred))

# 7. Exibir o Relatório de Classificação
print("\n=== RELATÓRIO DE CLASSIFICAÇÃO ===")
print(classification_report(y_test, y_pred))

# 8. Limiar de confiança para o Fallback
LIMIAR_CONFIANCA = 0.50

# 9. Estrutura interativa com 8 testes obrigatórios
print("\n=== INICIANDO BATERIA DE TESTES (8 INPUTS OBRIGATÓRIOS) ===")

for i in range(1, 9):
    print(f"\n[Teste {i}/8]")

    # Solicitar frase do usuário
    frase = input("Digite a frase do cliente: ").strip()

    # Obter a classe prevista
    intencao = pipeline_dt.predict([frase])[0]

    # Obter as probabilidades
    probs = pipeline_dt.predict_proba([frase])
    maior_prob = np.max(probs)

    # 10. Aplicar regra de decisão com Fallback
    if maior_prob >= LIMIAR_CONFIANCA:
        print(f"Intenção: {intencao}")
        print(f"Probabilidade: {maior_prob:.2%}")
    else:
        print("Desculpe, não entendi sua solicitação. Encaminhando você para um atendente humano...")



=== MATRIZ DE CONFUSÃO ===
[[4 0 0 0 2]
 [1 4 1 0 0]
 [0 0 6 0 0]
 [0 0 1 5 0]
 [0 0 0 1 5]]

=== RELATÓRIO DE CLASSIFICAÇÃO ===
                    precision    recall  f1-score   support

logistica_entregas       0.80      0.67      0.73         6
       reclamacoes       1.00      0.67      0.80         6
           suporte       0.75      1.00      0.86         6
 trocas_devolucoes       0.83      0.83      0.83         6
            vendas       0.71      0.83      0.77         6

          accuracy                           0.80        30
         macro avg       0.82      0.80      0.80        30
      weighted avg       0.82      0.80      0.80        30


=== INICIANDO BATERIA DE TESTES (8 INPUTS OBRIGATÓRIOS) ===

[Teste 1/8]
